spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: Qinye111..
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      validation-timeout: 250
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 180000
      maximum-pool-size: 15


